product: jvm/app

repositories:
  - id: aliyun-central
    url: https://maven.aliyun.com/repository/central
  - id: google
    url: https://maven.google.com
    resolve: false

test-dependencies:
  - $libs.kotest.assertions
  - $libs.kotest.framework
  - $libs.kotest.runner: runtime-only
